ENV["VAGRANT_DEFAULT_PROVIDER"] = "virtualbox"
Vagrant.configure("2") do |config|

  # OS IMAGE
  config.vm.box = "generic/ubuntu1804"

  # Network Config
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network", bridge: " "

  # Sync Folder
  config.vm.synced_folder ".", "/var/www/html"

  # Provider Config
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2

  # Provision
  #config.vm.provision "shell", inline: <<-SHELL
  #  apt-get update
  #SHELL

  config.vm.provision "shell", path: "bootstrap.sh"
  end
end