ENV["VAGRANT_DEFAULT_PROVIDER"] = "virtualbox"
Vagrant.configure("2") do |config|

  ## IMAGE ##
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "private_network", ip: "192.168.33.10"

  ## Provider Config ##
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2

  ## Provision ##
  config.vm.provision "shell", path: "bootstrap.sh"
  end
end